### ISSUE TITLE
Decoder support for big(?) endian values

### ISSUE THREAD

**Issue by ulabs-sgiroux** [linklayer/pyvit#14]
I'm not sure of the byte ordering for candump files (e.g. (time) interface msg_id#msg_Data) but I have a signal which spans bytes 6 and 7 (reading left to right) with 6 being the most significant byte.

My database.json's signal starts at bit 40, and has a bit_length of 16 but I believe the parser is treating bit 40 as the LSB (instead of MSB in my case)

Reference:
```
{
    "messages": [
        {
	    "name": "test msg",
            "id": "0x080",
	    "signals":
	    {
		"40":
		{
		    "name": "MSB Data",
		    "bit_length": 16,
		    "factor": 1,
		    "offset": 0
		}
	    }
        }
    ]
}
```

`
ID=0x080, DLC=8, Data=[90, 00, 7D, 00, 00, 80, 0E, F7]
`

**Comment by ericevenchick** [comment]
Closing this for now as the database stuff is very much WIP and might be replaced with Kayak / DBC formats...
