### ISSUE TITLE
getting started example fails

### ISSUE THREAD

**Issue by holla2040** [linklayer/pyvit#18]
on ubuntu x64 16.04, both 'pip install pyvit' and 'python setup.py install' results in error on set_bitrate, see below. 

```
>>> from pyvit import can
>>> from pyvit.hw.cantact import CantactDev
>>> dev = CantactDev("/dev/ttyACM0")
>>> dev.set_bitrate(500000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyvit-0.1.2-py2.7.egg/pyvit/hw/cantact.py", line 33, in set_bitrate
    self._dev_write('S6\r')
  File "/usr/local/lib/python2.7/dist-packages/pyvit-0.1.2-py2.7.egg/pyvit/hw/cantact.py", line 11, in _dev_write
    self.ser.write(bytes(string, encoding='ascii'))
TypeError: str() takes at most 1 argument (2 given)
```

**Comment by holla2040** [comment]
oops, requires python3, my bad. You should mention this in 

https://github.com/linklayer/pyvit/blob/master/docs/getting-started.rst

**Comment by holla2040** [comment]
You can run in python2 but python2's serial.write doesn't support encoding param) 
change line 11 in cantact.py 
    self.ser.write(bytes(string, encoding='ascii'))
to
    self.ser.write(bytes(string)

then first getting started example works in python2.

**Comment by ericevenchick** [comment]
This has been fixed by using `str.encode()`, which should do the right thing on both Python2 and Python3.
