### ISSUE TITLE
Clean Up Old Examples

### ISSUE THREAD

**Issue by txjacob** [linklayer/pyvit#23]
I am having a problem running the UDS.py example. It appears it's looking for some functions that no longer exist:

```
pi@raspberrypi:~ $ python3 uds.py 
Traceback (most recent call last):
  File "uds.py", line 3, in <module>
    from pyvit.proto.uds import UdsInterface
  File "/usr/local/lib/python3.4/dist-packages/pyvit/proto/uds.py", line 1, in <module>
    from pyvit.proto.isotp import IsoTpProtocol, IsoTpMessage
ImportError: cannot import name 'IsoTpProtocol'
```

**Comment by ericevenchick** [comment]
Hi,

Unfortunately, some of the examples are based on old versions of this code. I need to clean up examples, so thanks for the tip.

In this particular example, IsoTpProtocol has been fully reimplemented as IsotpInterface.

**Comment by txjacob** [comment]
I see you've already begun to fix it, awesome! I look forward to playing with it this weekend...
